CREATE TABLE STUDENTS(
        UUID INTEGER PRIMARY KEY,
        NAME TEXT,
        ADDRESS TEXT,
        PHONE TEXT
);

CREATE TABLE INSTRUCTORS(
        UUID INTEGER PRIMARY KEY,
        NAME TEXT,
        ADDRESS TEXT,
        PHONE TEXT
);
