DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS INSTRUCTORS;
DROP TABLE IF EXISTS RECORDS;

CREATE TABLE STUDENTS(
        UUID INT PRIMARY KEY,
        NAME VARCHAR(100),
        ADDRESS VARCHAR(100),
        PHONE VARCHAR(100)
);

CREATE TABLE INSTRUCTORS(
        UUID INT PRIMARY KEY,
        NAME VARCHAR(100),
        ADDRESS VARCHAR(100),
        PHONE VARCHAR(100)
);

CREATE TABLE RECORDS(
        STUDENT_ID INT NOT NULL,
		COURSE_ID INT NOT NULL,
		INSTRUCTOR_ID INT NOT NULL,
        COMMENT VARCHAR(100),
        GRADE VARCHAR(1)
);
